name: "Daikin Brasil"
description: "Add-on para Ar Condicionado compatível com o aplicativo Daikin Smart AC - Brasil"
version: "0.0.5"
slug: "daikin_brasil"
init: false
services:
  - mqtt:need
map:
  - addon_config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  reload_things: false
  reload_addresses: false
schema:
  daikin_email: email
  daikin_password: password
  reload_things: bool
  reload_addresses: bool
